#!/usr/bin/env Rscript

library(data.table)
library(BBmisc)

s = system3("squeue", stdout = TRUE, args = "-u $USER -o '%l %L %t'")$output

if (length(s) == 0) {
  cat("No jobs on system!\n")
} else {
  tab = read.table(textConnection(s), header = TRUE, stringsAsFactors = FALSE)
  tab = as.data.table(tab)
  
  # time conversion from character to seconds
  factors = c(24 * 60 * 60, 60 * 60, 60, 1)
  toSeconds = function(x) {
    z = strsplit(x, "-")[[1]]
    l = length(z)
    z2 = strsplit(z[l], ":")[[1]]
    l2 = length(z2)
    z3 = numeric(4)
    z3[(5 - l2):4] = as.numeric(z2)
    if (l > 1) z3[1] = as.numeric(z[1])
    res = sum(z3 * factors)
    return(res)
  }
  
  left = sapply(tab$TIME_LEFT, toSeconds)
  tab$TIME_LEFT = left
  
  # queue names
  limit = sapply(tab$TIME_LIMIT, toSeconds)
  walltimes = c(2 * 3600, 8 * 3600, 48 * 3600, 672 * 3600)
  names = c("short", "med", "long", "ultralong")
  names.limit = sapply(limit, function(x) names[min(which(x <= walltimes))])
  tab$TIME_LIMIT = names.limit
  
  tab1 = tab[, list(
    Running = sum(ST == "R"),
    Pending = sum(ST == "PD")
  ), by = c("TIME_LIMIT")]
  colnames(tab1)[1] = "Queue"
  
  cat("Number of running and pending jobs:\n")
  print(tab1, row.names = FALSE)
  
  tab.r = tab[ST == "R", ]
  if (nrow(tab.r) > 0) {
    tab2 = tab.r[, list(
      Min = min(TIME_LEFT),
      Mean = round(mean(TIME_LEFT)),
      Median = round(median(TIME_LEFT)),
      Max = max(TIME_LEFT)
    ), by = c("TIME_LIMIT")]
    
    # better units depending on times
    time.units = choices = c("days", "hours", "minutes", "seconds")
    tus = sapply(tab2$Median, function(m) {
      if (m < 60) return(4)
      else if (m < 60 * 60) return(3)
      else if (m < 24 * 60 * 60) return(2)
      else return(1)
    })
    
    for (i in seq_along(tus)) {
      tab2[i, 2:5] = round(tab2[i, 2:5] / factors[tus[i]], 2)
    }
    
    tab3 = cbind(tab2, Unit = time.units[tus])
    colnames(tab1)[1] = colnames(tab3)[1] = "Queue"
    
    cat("\n")
    cat("Remaining times of running jobs:\n")
    print(tab3, row.names = FALSE)
  }
}