#!/usr/bin/env python

# get loginname
import getpass
# send command to os
import subprocess

# known queues names
queue_names = ['short', 'med', 'long', 'ultralong']

# get jobs with format "Partition, User, Status, Cpus"
command = 'squeue -h -o "%.12P %u %t %C"'
jobs = subprocess.Popen([command], stdout = subprocess.PIPE, shell = True)
jobs = jobs.stdout.readlines()

# Function to add one queue name
def append_partition(queue, name):
  queue[name] = {}
  queue[name]['name'] = name 
  for st in ['R', 'Rcpu', 'PD', 'PDcpu']:
    queue[name][st] = 0
  return queue
# init dict: queue counter variable
que_tot = {}
que_usr = {}
for qn in queue_names:
  que_tot = append_partition(que_tot, qn)
  que_usr = append_partition(que_usr, qn)

# get user
user_name = getpass.getuser()

# Loop jobs
for job in jobs:
  # 0: Partition, 1: User, 2: Status, 3: Cpus
  job = job.split()
  part = job[0] 
  user = job[1] 
  status = job[2]
  cpus = int(job[3])
  # skip status CG
  if status not in ('R', 'PD'):
    continue
  # Check Partition
  if part not in que_tot.keys():
    que_tot = append_partition(que_tot, part)
    que_usr = append_partition(que_usr, part)
    queue_names.append(part)
  # Count
  que_tot[part][status] += 1
  que_tot[part][status + 'cpu'] += int(cpus)
  if user == user_name:
    que_usr[part][status] += 1
    que_usr[part][status + 'cpu'] += int(cpus)

# Output
table_format_header = '{:>14s} | {:^12s} | {:^12s}'
table_format = '{0[name]:>14s} | {0[R]:4d} - {0[Rcpu]:5d} | {0[PD]:4d} - {0[PDcpu]:5d}'
table_width = 44
# Function
def print_summary(queue, queue_names, table_format):
  total = {'name':'total', 'R':0, 'Rcpu':0, 'PD':0, 'PDcpu':0}
  for qn in queue_names:
    print(table_format.format(queue[qn]))
    for st in ['R', 'Rcpu', 'PD', 'PDcpu']:
      total[st] += queue[qn][st]
  print(table_format.format(total))
# Prints 
print(table_format_header.format('', 'Running', 'Pending'))
print(table_format_header.format('Queues', 'Jobs -  Cpus', 'Jobs -  Cpus'))
print(('{:-^' + str(table_width) + '}').format('Total'))
print_summary(que_tot, queue_names, table_format)
print(('{:-^' + str(table_width) + '}').format('User'))
print_summary(que_usr, queue_names, table_format)

