#!/usr/bin/env python

# get loginname
import getpass
# send command to os
import subprocess

# known queues names
queue_names = ['short', 'med', 'long', 'ultralong']

# get jobs
command = 'squeue -h -o "%.12P %u %t %C"'
jobs = subprocess.Popen([command], stdout = subprocess.PIPE, shell = True)
jobs = jobs.stdout.readlines()

# Function to add one queue name
def append_partition(queue, name):
  queue[name] = {}
  queue[name]['name'] = name 
  for st in ['R', 'Rnds', 'PD', 'PDnds']:
    queue[name][st] = 0
  return queue
# init queue counter variable (nds: number of nodes)
que_tot = {}
que_usr = {}
for qn in queue_names:
  que_tot = append_partition(que_tot, qn)
  que_usr = append_partition(que_usr, qn)

# get user
user_name = getpass.getuser()

# Loop jobs
for job in jobs:
  # 0: Partition, 1: User, 2: Status, 3: Cpus
  job = job.split()
	# skip status CG
  if job[2] == 'CG':
    continue
  # Check Partition
  if job[0] not in que_tot.keys():
    que_tot = append_partition(que_tot, job[0])
    que_usr = append_partition(que_usr, job[0])
    queue_names.append(job[0])
  # Count
  que_tot[job[0]][job[2]] += 1
  que_tot[job[0]][job[2] + 'nds'] += int(job[3])
  if job[1] == user_name:
    que_usr[job[0]][job[2]] += 1
    que_usr[job[0]][job[2] + 'nds'] += int(job[3])

# Output
table_format_header = '{:>14s} | {:^11s} | {:^11s}'
table_format = '{0[name]:>14s} | {0[R]:4d} - {0[Rnds]:4d} | {0[PD]:4d} - {0[PDnds]:4d}'
table_width = 42
# Function
def print_summary(queue, queue_names, table_format):
  tot = {'name':'total', 'R':0, 'Rnds':0, 'PD':0, 'PDnds':0}
  for qn in queue_names:
    print(table_format.format(queue[qn]))
    for st in ['R', 'Rnds', 'PD', 'PDnds']:
      tot[st] += queue[qn][st]
  print(table_format.format(tot))
# Prints 
print(table_format_header.format('', 'Running', 'Pending'))
print(table_format_header.format('Queues', 'Jobs - Cpus', 'Jobs - Cpus'))
print(('{:-^' + str(table_width) + '}').format('Total'))
print_summary(que_tot, queue_names, table_format)
print(('{:-^' + str(table_width) + '}').format('User'))
print_summary(que_usr, queue_names, table_format)

